version: '3.4'
services:
   jupyter:
      build: 
         context: ./network_statistics
         network: host
      container_name: jupyter
      restart: always
      user: '0'
      ports:
         - '8888:8888'
      volumes:
         - ./network_statistics:/home/jovyan/work